name: box-dev

services:
  web-server:
    build:
      context: .
      target: web-server-development
    extends:
      file: comum.yml
      service: web-server
    networks:
      - connection
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        
  application:
    networks:
      - connection
    depends_on:
      - web-server
    build:
      context: .
      target: app-development
    extends:
      file: comum.yml
      service: app-server
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: false

  database:
    build:
      context: .
      target: database
    extends:
      file: comum.yml
      service: database
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - connection

volumes:
  db-data:

networks:
  connection: