name: box-dev

services:
  web-server:
    build:
      context: .
      target: web-server-development
    extends:
      file: comum.yml
      service: web-server
    networks:
      - connection
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

networks:
  connection: