name: box-prod

services:
  web-server:
    build:
      context: .
      target: web-server-prodution
    extends:
      file: comum.yml
      service: web-server
    networks:
      - connection

  application:
    build:
      context: .
      target: app-prodution
    networks:
      - connection
    depends_on:
      - web-server
    extends:
      file: comum.yml
      service: app-server

  database: 
    build:
      context: .
      target: database
    extends:
      file: comum.yml
      service: database
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - connection

volumes:
  db-data:

networks:
  connection:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"